name: Migrate
  
on:
  push:
    branches: ["main"]

jobs:
  migrate:
    name: Migrate DB
    timeout-minutes: 15
    runs-on: ubuntu-22.04

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: 8.9

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Set variables
        id: setvars
        run: |
          if [[ "${{github.base_ref}}" == "main" || "${{github.ref}}" == "refs/heads/main" ]]; then
            export DATABASE_URL=$PROD_DATABASE_URL
          else  
            export DATABASE_URL=$STAGING_DATABASE_URL
          fi
        env:
          STAGING_DATABASE_URL: ${{ secrets.STAGING_DATABASE_URL }}
          PROD_DATABASE_URL: ${{ secrets.PROD_DATABASE_URL }}

      - name: Migrate Production DB
        run: pnpm migrate:deploy
        working-directory: ./apps/backend
        
  
