name: Migrate
  
on:
  push:
    branches: ["main"]

jobs:
  migrate:
    name: Migrate DB
    timeout-minutes: 15
    runs-on: ubuntu-22.04

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: 8.9

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      
      - name: Generate Prisma
        run: pnpm run prisma:generate
        working-directory: ./apps/backend

      - name: Migrate Production DB
        run:  pnpm migrate:deploy
        working-directory: ./apps/backend
        env:
          DATABASE_URL: ${{ secrets.STAGING_DATABASE_URL }}
          DIRECT_URL: ${{ secrets.STAGING_DIRECT_URL }}

        
  
